name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 160.251.139.45
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd douzo/ && git pull && docker-compose build && docker-compose up -d && docker exec -it douzo_app_api_1 /bin/bush -c 'pytest -s tests/test_hoge.py'
